# /wordpress-docker/docker-compose.yml
# Reference: https://yoast.com/developer-blog/set-up-wordpress-development-environment-in-docker/
---
version: '3.8' # Min version of docker compose file format
services:
  db:
    container_name: 'local-wordpress-db'
    image: 'mysql:5.7' # Official MySQL 5.7 Docker image
    volumes:
    # Maps folders from your computer to folders inside of 
    # the container.
      - './data/mysql:/var/lib/mysql'
    ports:
    # Maps a server port from your computer to a server 
    # port inside of the container.
      - 18766:3306
    environment:
    # Environment variables for the container
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
  wordpress:
    container_name: 'local-wordpress'
    depends_on:
      - db
    image: 'wordpress:latest' # Official WP Docker image
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - './wordpress:/var/www/html'
      - './plugins:/var/www/html/wp-content/plugins'
      - './themes:/var/www/html/wp-content/themes'
    
